spring:
  kafka:
    consumer:
      group-id: tpd-loggers
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: ${spring.embedded.kafka.brokers}

topic:
  name: sample-topic
  messages-per-request: 3
